services:

  catalog-db:
    container_name: catalog-db    
    image: postgres:latest   
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./posgres/db:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - catalog-db
    container_name: ${PG_DB_NAME}
    image: dpage/pgadmin4
    ports:
      - "5174:80"
    volumes:
      - ./pgadmin:/var/lib/pgadminv 
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: ${PG_USERNAME}
    restart: always
  
  mongo-db:
    container_name: ${MONGO_DB_NAME}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    # ports:
    #   - "27017:27017"
    restart: always
    command: ['--auth']    

  mongo-express:
    depends_on:
      - mongo-db
    image: mongo-express
    restart: always
    ports:
      - 8081:8081    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}      
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
     # ME_CONFIG_MONGODB_URL: mongodb:// ${MONGO_USERNAME:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017/

# volumes:
#    postgres_catalog:
#    external: false


