services:

  # catalog-api:
  #   container_name: catalog-api
  #   build:
  #     context: ./catalog-api
  #     dockerfile: Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  catalog-db:
    container_name: catalog-db    
    image: postgres:latest   
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./posgres/db:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - catalog-db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5174:80"
    volumes:
      - ./pgadmin:/var/lib/pgadminv 
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_DEFAULT_EMAIL=jau@google.com

# volumes:
#    postgres_catalog:
#    external: false


